
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=academy'
      - 'POSTGRES_PASSWORD=n8rP@Zq#4LxV!gTw1KdB'
      - 'POSTGRES_USER=academy'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: apple-academy-api:0.0.1-SNAPSHOT
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/academy
      - SPRING_DATASOURCE_USERNAME=academy
      - SPRING_DATASOURCE_PASSWORD=n8rP@Zq#4LxV!gTw1KdB
    depends_on:
      - postgres

volumes:
  postgres-data: